# Generated by Django 4.1.6 on 2023-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linkdetailM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=250)),
                ('date', models.TextField(max_length=50)),
                ('risk', models.TextField(max_length=50)),
                ('cve', models.TextField(max_length=50)),
                ('cwe', models.TextField(max_length=50)),
            ],
        ),
    ]
